### ISSUE TITLE
Screenly stops displaying assets

### ISSUE THREAD

**Issue by tomcrummey** [Screenly/Anthias#100]
After installing the latest version of screenlyOSE on 4 Raspberry PI systems, and leaving them running displaying 18 images for 30s each, I found that this morning, no images are being displayed. The system status log shows:

Thu, 14 Mar 2013 12:05:07 Browser loaded. Running as PID 14605.
Thu, 14 Mar 2013 12:05:18 Generating asset-list...
Thu, 14 Mar 2013 12:06:26 Loading browser...
Thu, 14 Mar 2013 12:06:27 Browser loaded. Running as PID 14645.
Thu, 14 Mar 2013 12:06:38 Generating asset-list...
Thu, 14 Mar 2013 12:07:47 Loading browser...
Thu, 14 Mar 2013 12:07:48 Browser loaded. Running as PID 14685.
Thu, 14 Mar 2013 12:07:59 Generating asset-list...
Thu, 14 Mar 2013 12:09:07 Loading browser...
Thu, 14 Mar 2013 12:09:09 Browser loaded. Running as PID 14722.
Thu, 14 Mar 2013 12:09:20 Generating asset-list...
Thu, 14 Mar 2013 12:10:29 Loading browser...
Thu, 14 Mar 2013 12:10:30 Browser loaded. Running as PID 14759.
Thu, 14 Mar 2013 12:10:41 Generating asset-list...
Thu, 14 Mar 2013 12:11:50 Loading browser...
Thu, 14 Mar 2013 12:11:52 Browser loaded. Running as PID 14799.
Thu, 14 Mar 2013 12:12:03 Generating asset-list...
Thu, 14 Mar 2013 12:13:17 Loading browser...
Thu, 14 Mar 2013 12:13:18 Browser loaded. Running as PID 14849.
Thu, 14 Mar 2013 12:13:29 Generating asset-list...

The screens themselves are blank.

All the images are set to expire on 31st December 2013 at 12:00AM. Are there any other logs I can use to debug what is going on?

Thanks

**Comment by vansatchen** [comment]
Same trouble. Resolved by editing 
disable_update_check = getenv("DISABLE_UPDATE_CHECK", False)
to 
disable_update_check = getenv("DISABLE_UPDATE_CHECK", True)
in screenly/viewer.py

**Comment by vpetersson** [comment]
@vansatchen That has been fixed in the development branch.
