### ISSUE TITLE
Ability to set Pi date and Time from Screenly settings

### ISSUE THREAD

**Issue by magnets99** [Screenly/Anthias#115]
Enhancement:
Ability to set Pi date and Time from Screenly settings

When using Screenly within a closed LAN or a network with heavy fire-walling and no NTP server the PI cannot determine it's date and time. This leads to unexpected behavior when setting the start and finish dates of assets.
see bug 111 which was not an issue, but crippled functionality until the time was set manually via ssh. SSH is beyond the ability of most digital signage end users.

**Comment by pletiplot** [comment]
NTP is good, but sometime I need to use a different time server (i.e. inside a company). It would be good to have ability to change it.

**Comment by vpetersson** [comment]
@pletiplot Sure, but it's a regular Linux system. You can change it directly there.

**Comment by pletiplot** [comment]
@vpetersson You are right, I finally got the console and altered the settings. Actualy it took longet to learn that the empty" playlist is because of the wrong time :-)
