### ISSUE TITLE
Server Error: Could not retrieve file. Check the asset URL.

### ISSUE THREAD

**Issue by Sunspiral** [Screenly/Anthias#124]
I'm trying to display a public HTML Google Calendar and I'm getting the following error message:

Server Error: Could not retrieve file. Check the asset URL.

Any ideas?

Thanks.

**Comment by vpetersson** [comment]
This has been resolved in master. Just run the upgrade script:

    $ bash <(curl -sL https://www.screenlyapp.com/install-ose.sh)
