### ISSUE TITLE
Port 8080 ?

### ISSUE THREAD

**Issue by DArKo91** [Screenly/Anthias#137]
Hi,
I'd like to know where the 8080 port is configured.
I tried to change it in files : 
- screenly/settings.py :: 'listen': '0.0.0.0:8080'
- screenly/misc/screenly.conf :: listen = 127.0.0.1:8080
  and no change after services reboot...

Thanks.

**Comment by Charly85** [comment]
Hi,

Can we still change the port configuration in the latest version?

Thanks.

**Comment by vpetersson** [comment]
In theory, yes, but I haven't done that test myself. You will likely need to udpate both the application port and the port that Nginx binds to.
