### ISSUE TITLE
Can't build on balena

### ISSUE THREAD

**Issue by mmclane** [Screenly/Anthias#1587]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Can't build for balena any more.. 

When running ./bin/deploy_to_balena.sh with the latest balena cli you get an error:

 4:13PM: ~/repos/public/screenly-ose [master|✔] k8s:[main] > ./bin/deploy_to_balena.sh
Here are your Balena apps:
Note: the command "balena apps" was replaced in CLI version v13.0.0.
Please use "balena fleets" instead.

I upgraded to the latest version because I was getting other errors.

If I modify line 23 of ./bin/deploy_to_balena.sh and change it to balena fleets, I get further but still an error:

```
Here are your Balena apps:
ID      NAME         SLUG                    DEVICE TYPE  ONLINE DEVICES DEVICE COUNT
1946063 screenly     docnetwork/screenly     raspberry-pi 1              1
1880537 screenly-ose docnetwork/screenly-ose raspberrypi3 1              1

Enter the app name of the app you want to deploy to (needs to be SLUG): docnetwork/screenly
app is not a recognized balena command.

Did you mean: ? 
  api-key generate
  key

Run balena help -v for a list of available commands,
 or balena help <command> for detailed help on a specific command.

```

#### Reproduction Steps

Download balena cli v13.6.1 (latest)
run ./bin/deploy_to_balena.sh

#### Environment

* Raspberry Pi Hardware Version:
* Raspberry Pi Network Setup: (ex. built-in WiFi, Ethernet, USB WiFi Adapter)
* Screenly OSE Version:

**Comment by mmclane** [comment]
This is on a raspberry pi zero W.  

I have also tried to install screenly on the device without balena and have failed to get that to work too.

**Comment by mmclane** [comment]
Oh, am I am using a monitor plugged in via HDMI currently.

**Comment by vpetersson** [comment]
This should have been resolved in #1599

**Comment by vpetersson** [comment]
It's unclear why, but the build phase of balena still doesn't work properly.

**Comment by mmclane** [comment]
I am definitely still getting the same error.

**Comment by vpetersson** [comment]
We are working on revamping how we support Balena. Stay tuned for updates, but in the meantime, we are now automatically deploying to Balena [as part of CI](https://github.com/Screenly/screenly-ose/blob/master/.github/workflows/docker-build.yaml#L106). You should be able to just mimic what we're doing there in the meantime.

**Comment by nicomiguelino** [comment]
@mmclane, we have already revamped the [docs for deploying Anthias on your own Balena fleets/devices](https://github.com/Screenly/Anthias/blob/0fd729b019c61260059556c751dd328ec78fee77/docs/balena-fleet-deployment.md).

Please reopen this issue if you're still facing similar issues.
