### ISSUE TITLE
Resolve issue with balena-wifi-connect (former resin-wifi-connect)

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Anthias#1628]
It appears as we've broken the WiFi configuration somewhere along the upgrade process (either in Bullseye or in the containerization).

Since we're using an old version, the first process would probably be to upgrade it (we're still using resin-wifi-connect rather than balena-wifi-connect). Hopefully that will get us going.

**Comment by nicomiguelino** [comment]
As mentioned by Viktor on Slack, might read up on what `raspi-config` does when enabling the Wi-Fi.
- Enabling Wi-Fi via `raspi-config` might introduce side effects.
