### ISSUE TITLE
Set Balena device and/or fleet configs programmatically.

### ISSUE THREAD

**Issue by nicomiguelino** [Screenly/Anthias#1661]
#### General

- ~This issue aims to automate the modification of relevant config params relevant to #1651.~

#### Tasks

- [x] Modify relevant GitHub workflow files so that fleet-wide configs can be set programmatically.

#### Strategy

- Make use of [balena-io-experimental/community-cli-action](https://github.com/balena-io-examples/community-cli-action) to ensure that fleet configs are properly set.

**Comment by nicomiguelino** [comment]
@vpetersson, here's a sample command for setting fleet configs programmatically (via Balena CLI):

```bash
# balena env add $CONFIG_VARIABLE $VALUE --fleet $FLEET_NAME
balena env add RESIN_HOST_CONFIG_gpu_mem 512 --fleet anthias-pi4
balena env add RESIN_HOST_CONFIG_dtoverlay vc4-fkms-v3d --fleet anthias-pi4
```

For automation, these commands can be used in a shell script.

**Comment by vpetersson** [comment]
> @vpetersson, here's a sample command for setting fleet configs programmatically (via Balena CLI):
> 
> ```shell
> # balena env add $CONFIG_VARIABLE $VALUE --fleet $FLEET_NAME
> balena env add RESIN_HOST_CONFIG_gpu_mem 512 --fleet anthias-pi4
> balena env add RESIN_HOST_CONFIG_dtoverlay vc4-fkms-v3d --fleet anthias-pi4
> ```
> 
> For automation, these commands can be used in a shell script.
> 
> I'll be closing this issue now, as this is a one-time setup, esp. for new fleets.

Yes, but these values are different for different devices.

**Comment by nicomiguelino** [comment]
Thanks for pointing that one out, @vpetersson. But can the values be the same for devices of the same fleet?
(I can include docs for setting config values for a specific device).
