### ISSUE TITLE
French translations ?

### ISSUE THREAD

**Issue by forum6691** [Screenly/Anthias#1690]
Hi Victor.
Seven years ago (a long time now), I asked for you a French version of screenly OSE.

Today , I propose me again to make a translation in French of the Anthias version (new name) if ther is a xml file with the different char strings used in the software .

Do you think it was possible ?

**Comment by vpetersson** [comment]
Thank you for offering this @forum6691, but I'm not sure I want to go down the path of translations at this point as it adds a lot of overhead in development.

**Comment by vpetersson** [comment]
Sure, but it is unlikely for the foreseeable future.
