### ISSUE TITLE
Demo site asks for username/password

### ISSUE THREAD

**Issue by jobridts** [Screenly/Anthias#1704]
https://ose.demo.screenlyapp.com/ asks for username and password.

according to #1596 there is probably something worng with the demo (cleanup?)

**Comment by jschwalbe** [comment]
Was hoping to see the live demo.. seems it's still broken.

**Comment by vpetersson** [comment]
Users keep breaking the demo site by adding a password to it to lock out other users. We've shut down the demo site for now. 

You can easily spin up a local demo site with the following commands:

```bash
$ git clone https://github.com/Screenly/Anthias.git
$ cd Anthias
$ docker-compose \
    -f docker-compose.dev.yml build
$ docker-compose \
    -f docker-compose.dev.yml up
```
