### ISSUE TITLE
New Docker Deployment fails to start

### ISSUE THREAD

**Issue by altafs** [Screenly/Anthias#1706]
I'm Evaluating a local Anthias Server via DOCKER IMAGE followed the steps described in README for Docker Image Generation
it successfully generates 4 Docker Containers under 
anthias-master
![anthias_master](https://user-images.githubusercontent.com/8613243/211265521-d5d3248e-eec9-42ec-acf6-0a23815d9b93.jpg)

The Log  states : error while interpolating services.srly-ose-viewer.mem_limit: failed to cast to expected type: invalid size: 'k'
![antheas-mast1](https://user-images.githubusercontent.com/8613243/211265857-ead46cbc-5305-4577-b570-3691363c20ae.jpg)

**Comment by vpetersson** [comment]
So you can't run an 'Anthias server' in the sense that you can run it separately. Everything needs to run locally on the device.

Please use the installation script which sets all these variables.
