### ISSUE TITLE
What browser is used in Screenly OSE to render a web page

### ISSUE THREAD

**Issue by alex-levashev** [Screenly/Anthias#1720]
Hello,

As you probably know, not all web pages are displayed correctly on Screenly OSE. I want to precheck a web page before posting it to the Screenly. What browser should I use in order to do that correctly.

Thanks in advance for the answer.

**Comment by vpetersson** [comment]
You can't easily. Most pages should render just fine with the browser we are using now (less inline videos etc). It was more an issue when we used UZBL, which was very dated by the end. 

The browser we use now is [Webview](https://doc.qt.io/qt-5/qtwebview-index.html) from QT.
