### ISSUE TITLE
 Set zoom level for Assets

### ISSUE THREAD

**Issue by TiWe1998** [Screenly/Anthias#1721]
Hello, I'm looking for a way to set the zoom level. Unfortunately I found an old manual. I cannot find the folder or file in the current image.

And another small question: Is it correct that the various websites are completely updated again and again or do they remain as they were when they were first started?

BR

**Comment by TiWe1998** [comment]
Yes!

**Comment by ealmonte32** [comment]
Thanks.
You should close this issue on here after you post on forums.

**Comment by TiWe1998** [comment]
I posted it in the forum. It has yet to be released. Thanks! Can be closed here.

**Comment by ealmonte32** [comment]
> I posted it in the forum. It has yet to be released. Thanks! Can be closed here.

can you just close this yourself? otherwise i have to bother someone else to close.
