### ISSUE TITLE
Fix header of new design

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Anthias#1726]
When toggling between Schedule Overview, Settings and System Info, the content container jumps (in particular between Settings and System Info). Could you please look into this?

<img width="1139" alt="Screenshot 2023-02-07 at 9 42 41 AM" src="https://user-images.githubusercontent.com/357664/217208899-141fec34-2592-4128-bcea-700e916ae5bb.png">
<img width="1193" alt="Screenshot 2023-02-07 at 9 42 46 AM" src="https://user-images.githubusercontent.com/357664/217208907-91215328-a752-461f-a9d3-4aea5618f553.png">
<img width="1209" alt="Screenshot 2023-02-07 at 9 42 57 AM" src="https://user-images.githubusercontent.com/357664/217208912-ce3b3921-64b1-455e-8a76-c998e1392725.png">

**Comment by nicomiguelino** [comment]
@vpetersson, on it...
