### ISSUE TITLE
Black screen after splashscreen

### ISSUE THREAD

**Issue by marcusmoller01** [Screenly/Anthias#1759]
#### Overview of the Issue

After downloading anthias and rebooting the raspberry i see the splashscreen with anthias logo but then it goes dark and i dont get the connect ip screen. And im not able to connect from a browser to the raspberrys ip. 

#### Reproduction Steps
I downloaded anthias via bash <(curl -sL https://install-anthias.srly.io) then after rebooting i get the splashscreen followed by a black screen. 

When trying to troubleshoot i ran journalctl and got this:
![journactl error](https://user-images.githubusercontent.com/126557202/221806825-2fd4b9b7-bbe7-48f7-87e6-5b3bbd6010af.jpg)

So i downloaded redis-server manually and rebooted again but anthias still doesnt run. When doing journalctl i dont seem to have problem with redis-server and get no error message:

![journalno error](https://user-images.githubusercontent.com/126557202/221807357-426ac593-1734-45a3-92c3-5e2bcb4752f4.jpg)

So then i tried the command ./screenly/bin/upgrade_containers.sh and got the following error message:

![error docker](https://user-images.githubusercontent.com/126557202/221807797-03bf9a77-88d7-4b65-ac8c-40ee94d2320a.jpg)

And docker-compose build .... is not runnable on the raspberry.
Any ideas where the problem may be and how i can approach to fix it?
Any help appreciated!

EDIT:
Was a problem with the proxy settings for docker but is now fixed and succesfully installed. But anthias cant connect to an URL so i suspect its the same proxy issue with anthias. How do i set edit the proxy settings fro anthias/screenly?

#### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 3 Model B Rev 1.2 with OS Debian GNU/Lunyx 11 (bullseye) 64 bit
* Raspberry Pi Network Setup: Ethernet

* Anthias Version: Latest

**Comment by vpetersson** [comment]
Right. Yes, proxy isn't supported.
