### ISSUE TITLE
IP address previewed on the splash screen doesn't update

### ISSUE THREAD

**Issue by renemeijering** [Screenly/Anthias#1766]
Recently i have installed several raspberry pi's with Anthias. During installation i noticed that the IP address set during installation and setting up Anthias is stored in the splash screen, however the displayed IP address never updates.  When changing the device configuration to a fixed IP address or switching to WiFi doesn't effect the displayed IP address during startup. Is there a way to fix this?

#### Environment

* Tested on Raspberry Pi Hardware Version: 4, 3B+ and 3B
* Raspberry pi OS: Bullseye Lite 32 bit
* Raspberry Pi Network Setup: Both wifi and wired 
* Anthias Version: master@df00592

**Comment by nicomiguelino** [comment]
@renemeijering, the only current way to update the IP address(es) shown on the splash screen is to run the following inside the `~/screenly/` directory:

```bash
./bin/upgrade_containers.sh
```
]

Take note that running `./bin/upgrade_containers.sh` will also pull the latest images from Docker Hub.
You can also run the following and then restart the containers:

```bash
export MY_IP=$(ip -4 route get 8.8.8.8 | awk {'print $7'} | tr -d '\n')
docker compose down && docker compose up -d
```

Another workaround to try is to add the `export` statement (as shown above) inside your `~/.bashrc` for instances running RPiOS Lite.

We're prioritizing fixing issues related to Python 2 to 3 migration and Wi-Fi connectivity.
We'll get back to this one later on.
