### ISSUE TITLE
Balena Setup Instructions missing critical info

### ISSUE THREAD

**Issue by blevien** [Screenly/Anthias#1831]
**In the Balena install instructions here:** https://github.com/Screenly/Anthias/blob/master/docs/balena-fleet-deployment.md

There is no documentation about what is supported for`$BOARD_TYPE`. Through a lot of trial and error, I was able to figure out that `pi4` worked, but couldn't find anything stating this in the docs or on the web.

```
$ ./bin/deploy_to_balena.sh \
    --board $BOARD_TYPE \
    --fleet $FLEET_NAME \
```

**Comment by nicomiguelino** [comment]
Hello @blevien! Thanks for raising this up. I hope the PR #1832 works. Feel free to add review comments to the PR.

**Comment by blevien** [comment]
Wow, thanks for the quick reply!!
