### ISSUE TITLE
Anthias recent builds

### ISSUE THREAD

**Issue by extremeskillz** [Screenly/Anthias#1839]
Hi team. How are we doing with updating the script for raspbian os bookworm? Fresh anthias builds are breaking under this os and took a hour to realize that raspbian updates to bookworm from bullseye(legacy). I install bullseye and the script worked fine. Will there be a script update to be backward compatible with both bullseye and bookworm?

From the issues log it looks like your working on it. I was able to get a new build up and running with bullseye but was curious on the updates??

**Comment by vpetersson** [comment]
Please see [this PR](https://github.com/Screenly/Anthias/pull/1836).
