### ISSUE TITLE
Server Error: name 'mplayer' is not defined 

### ISSUE THREAD

**Issue by ismailakincom** [Screenly/Anthias#1843]
<img width="642" alt="Screenshot at Dec 06 11-47-22" src="https://github.com/Screenly/Anthias/assets/6472427/ae598ece-a718-4367-bd52-2934881aad8e">
 When I add the rtmp://...... link, mplayer gives an error. It does not play streaming video. Could you help

**Comment by salmanfarisvp** [comment]
Hello @ismailakincom ,

Thank you for raising this issue. It seems that this concern has already been addressed in another active issue https://github.com/Screenly/Anthias/issues/1638 . To avoid fragmentation of discussions, I'd kindly suggest checking and contributing to the ongoing conversation there.

If you believe there are additional aspects or new insights to consider, please feel free to share them in the existing thread. Your input would be greatly appreciated!

Thank you for your understanding and contributions to the project.
