### ISSUE TITLE
I am looking to switch the display in portrait mode

### ISSUE THREAD

**Issue by Ezana-AI** [Screenly/Anthias#1852]
I have successfully installed Raspberry Pi Bullseye Lite x64 on an SD Card and configured SSH. Everything is working well; I can access it using Putty without any issues. Now, I need to rotate our TV screen to portrait mode. Could anyone please assist me in changing the orientation to portrait on my Raspberry Pi anthias or through Putty?

**Comment by salmanfarisvp** [comment]
@Ezana-AI , Please close this issue and continue the discussion here https://github.com/Screenly/Anthias/issues/1537#issuecomment-1874998041 . 

Thanks.
