### ISSUE TITLE
Pi LITE error

### ISSUE THREAD

**Issue by vatsake** [Screenly/Anthias#1857]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
The Curl command will result in errors

#### Reproduction Steps
1. Use Pi Lite OS
2. Run Curl command
3. Nothing happens after installing stuff (there will be errors)

The solution:
https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3

**Comment by nicomiguelino** [comment]
@vatsake, the 'pip' issue has already been resolved by #1836, where the installer was fix so that it could be compatible with Bookworm. I'll be closing this one.

About the blank screen between assets, there's a separate issue for that: #1851
