### ISSUE TITLE
10.1 on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by TrabNereelc** [Screenly/Anthias#1858]
Tried to download and install the Screenly 10.1 sprint relaese. Loaded it onto the SDHC card with Imager, rebooted. Connected an HDMI cable and a keyboard, but the PI does not appear to be booting.
Can the 10.1 image be downloaded and ran on a PI3B+
Tried to run the manual install (Install Debian Bullseye and install manually with the bash command) and that was working. This however is the latest release I guess, but I would need the 10.1.
Any way of installing the 10.1 manually or make the downloaded image work?
Raspberry Pi 3B+
SDHC Card: 32 GB

**Comment by vpetersson** [comment]
You will need Ethernet for the disk image to work, as it needs to self-update on boot.

**Comment by TrabNereelc** [comment]
I hooked up an ethernet cable and rebooted a couple of times, but the behavior remains the same unfortunately.
The ACT led blinks 4 times slow and 7 times fast.

**Comment by vpetersson** [comment]
Strange. @nicomiguelino is working on an updated disk image. Could be a Pi 4 with a new firmware that causes issue possibly. But that's just a wild speculation.

**Comment by TrabNereelc** [comment]
OK, no problem, thanks. Installed the latest version and is doing the same thing.
All OK for the moment.
Can be marked as closed
