### ISSUE TITLE
Server Error: Could not retrieve file. Check the asset URL.

### ISSUE THREAD

**Issue by asaunders7** [Screenly/Anthias#188]
When I attempt to add a url for a public google calendar to the asset page I get the error "Server Error: Could not retrieve file. Check the asset URL." Here is the url: https://www.google.com/calendar/embed?src=jim.larosa%40ametek.com&ctz=America/New_York

**Comment by vpetersson** [comment]
This has been resolved in master. Just run the upgrade script:

    $ bash <(curl -sL https://www.screenlyapp.com/install-ose.sh)
