### ISSUE TITLE
edits to cmdline.txt in wrong location

### ISSUE THREAD

**Issue by jdarmst** [Screenly/Anthias#1892]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

The ansible playbook edits /boot/cmdline.txt for several things. This is not longer the correct location for this file. It's at /boot/firmware/cmdline.txt.

#### Reproduction Steps

use install script on fresh install of raspbian lite 12 (bookworm)
check /boot/cmdline.txt

#### Environment

* Raspberry Pi Hardware Version: 3b+
* Raspberry Pi Network Setup: ethernet
* Anthias Version: latest as of today (5/8/2024)

**Comment by nicomiguelino** [comment]
@jdarmst, thanks for noticing this. Editing the correct cmdline.txt could fix #1878.

**Comment by nicomiguelino** [comment]
@jdarmst, please take a look at #1893 if you like to go into details. I'm still testing the changes though. #1878 is a known issue in devices running Bookworm. I hoe that the blinking top-left cursor goes away after the changes.
