### ISSUE TITLE
Anthias stuck on Screenly screen

### ISSUE THREAD

**Issue by Stevemberg** [Screenly/Anthias#1928]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, eg:

- Format SD to NTFS or FAT32
- Use Imager or Balena (image from repository or downloaded) to make the recording
- Put the SD in the Raspberry pi
- Connect the network and video cables
- Turn on rasp
- Access the web page with the IP shown
- Upload an asset (image or URL)
- The screen with the Screenly logo does not change
![4](https://github.com/Screenly/Anthias/assets/71530342/97c60934-e35e-4757-aa37-51408f43a6fe)
![Capturar](https://github.com/Screenly/Anthias/assets/71530342/8d5b0517-564b-4645-aee0-c94775003493)
![Capturar1](https://github.com/Screenly/Anthias/assets/71530342/630076c8-90ff-4ab8-8aa6-b11cd4f80ca5)
![Capturar3](https://github.com/Screenly/Anthias/assets/71530342/816ee3fa-1b88-483d-b356-b483eb5b16b9)

#### Environment

* Raspberry Pi Hardware Version: RP 3B rev 1.2
* Raspberry Pi Network Setup: Ethernet
* Anthias Version: master@48e427b

**Comment by nicomiguelino** [comment]
@Stevemberg
- How about adding another image asset?
- Have you tried adding a video asset or a web asset? Is the display stuck at the loading screen if its the only active asset?

**Comment by Stevemberg** [comment]
- Yes, many images with differents formats and sizes.
- Yes, video don't change anything. Yes, same screen with many or one asset active

**Comment by nicomiguelino** [comment]
@Stevemberg, I can see that the device name is not present. Since Anthias for Balena is a public fleet (see [Fleets for Good](`vc4-kms-v3d`) for details), fleet owners can access and monitor devices. Upon checking the device UUID, it seems that its non-existent on my end.

**Comment by Stevemberg** [comment]
The device is not on the internet, just on an intranet.

**Comment by Stevemberg** [comment]
I reinstalled one on another SD card and only turned it on when there was internet and then it got stuck on another splash screen.
![3](https://github.com/Screenly/Anthias/assets/71530342/a1a4e23b-3fab-46ec-abc4-9f7aa9d395cf)
I formatted the first SD and left it only on the intranet and it stuck on the same screen as the beginning of the issue.

**Comment by nicomiguelino** [comment]
@Stevemberg, is your device that's connected to the Internet still stuck at the splash screen? For Raspberry Pi 3 devices, it will take a while for the resources to be finished downloading.

**Comment by Stevemberg** [comment]
SOLVED! 
Leaving it connected to the internet for 20 minutes on the first boot solved the problem! Thanks for the tip that it would take a long time to download the resources.
Sorry for my inexperience, this is my first time working with embedded systems and IoT.
