### ISSUE TITLE
Typing error in Upgrade-Instructions

### ISSUE THREAD

**Issue by traeu** [Screenly/Anthias#1968]
#### Overview of the Issue

![grafik](https://github.com/Screenly/Anthias/assets/83320002/89f0ebb7-0f10-4313-9dec-89f9a5a1343e)

New Anthias versions show instructions for upgrading. There could be some improvements:

1. Instructions show names of variables, not the content of the variables
"ssh $USER@$HOSTNAME". Maybe it was intended to show something like "ssh pi@screenlypi" instead?

2. Path/name of upgrade-script is wrong.
"./bin_run_upgrade.sh" doesn't exist. I guess this should say "./bin/run_upgrade.sh" instead.

**Comment by nicomiguelino** [comment]
@traeu, thanks for your contribution (creating helpful issues does count). I'll let you know when I sort it out.
