### ISSUE TITLE
Monitor Info: Unable to run tvservice

### ISSUE THREAD

**Issue by traeu** [Screenly/Anthias#1999]
#### Overview of the Issue

After updating to latest anthias-version last week, I see "unable to run tvservice." at the System Info page.
I made another update a few minutes ago, the error message is still there.
It's not a big problem for me, I just noticed it and wanted to tell you.

![grafik](https://github.com/user-attachments/assets/fb17ef97-1e24-40cb-859e-cb79a5367b85)

**Comment by dfoley** [comment]
Also having this problem now on multiple Pi3 and Pi4 setups.

**Comment by vpetersson** [comment]
This is really just a display issue. Really doesn't have any practical implications (beyond not being able to see the output of `tvservice`).

**Comment by nicomiguelino** [comment]
@dfoley, @vpetersson
Bookworm dropped support for `tvservice`. Either the field shall be removed or use `vcgencmd` instead, if possible.
