### ISSUE TITLE
unable to add url from another local machine on network

### ISSUE THREAD

**Issue by stagea09** [Screenly/Anthias#214]
trying to display a webpage displayed that is hosted on our windows servers. url is "http://XX.XX.XXX.XX/slideshow/index.php"
just states it cant retrieve file.

**Comment by darshinvyas** [comment]
Hi VP,

Does screenly support authentication now? I see this is back in 2014. Any updates on this one? Am in a similar situation here.

Cheers,
Darshin

**Comment by vpetersson** [comment]
Yes, there's experimental support for authentication, but this is strictly limited to:
 * Basic auth
 * Authentication *to* Screenly

**Comment by stagea09** [comment]
No idea mate. Started using xibo instead

**Comment by sydrv** [comment]
Hi vpetersson,
currently I've the same problem with NTLM authentication and I'm very interested in a solution. Are there any updates to this topic? In my company the intranet policy doesn't allow anonymous calls of a website but it would be very nice to use screenly to display these websites. In your viewer.py script you are using the "uzbl" browser would it be possible to use something like this https://github.com/jborean93/ntlm-auth to add the NTLM authentication to the http request?
