### ISSUE TITLE
[BUG] Blinking cursor in top left

### ISSUE THREAD

**Issue by iLikeToCode** [Screenly/Anthias#2181]
**Describe the bug**

Top left blinking cursor still showing, despite being 'removed' in a previous release

**To Reproduce**

1. Install Anthias
2. Observe top left of screen

**Expected behavior**

The normal Anthias splash screen without anything else

**Environment:**

- Device: Raspberry Pi 4
- OS: Raspberry Pi OS 64-bit Bookworm
- Anthias Version: latest
- Installation Method: Manual Installation

**Comment by iLikeToCode** [comment]
Fixed after new install and reboot.

**Comment by nicomiguelino** [comment]
@iLikeToCode
Yes, the top-left blinking cursor will still be there unless you do a reboot.
Thanks.
