### ISSUE TITLE
Using mouse in kiosk mode

### ISSUE THREAD

**Issue by sirkserac** [Screenly/Anthias#238]
hello,

is it possible to configure uzbl to use a mouse in kiosk mode whit screenly ose?
we sometimes need te possibility to use a mous.

thx

ps: the mous is recognized when we plug it in

**Comment by jallen2281** [comment]
Honest? Who's being honest here, the poor guy just wanted to know where to find a simple setting! Anyways, Linux is Linux and screenly uses matchbox window manager launched by systemd. 

Change `ExecStart=/usr/bin/matchbox-window-manager -use_titlebar no -use_cursor no
` to `ExecStart=/usr/bin/matchbox-window-manager -use_titlebar no -use_cursor yes
` in /etc/systemd/system/matchbox.service, and reboot your pi and you should see your mouse working. We use mice with a number of our screenly Pi's

**Comment by vpetersson** [comment]
@jallen2281 There is a good reason why we have disabled user input in Screenly. Partially because it is an attack vector (the system is not hardened for this), but perhaps more importantly, it will provide a poor user experience.

In a kiosk, you want a timeout based system, such that if there is no user input for N seconds, restore to the default page. Screenly is not designed for this. It will simply reset the page after N seconds (which very well be while the user is inputting some data).

**Comment by jallen2281** [comment]
@vpetersson While that may hold true for a public kiosk, we are using them as personal wallboards that display device information that when in alarm may require a click to to get further details. Screenly works wonderful for this with the mouse enabled. No need for a timeout in this use case, which seems like it would be common for OSE.

**Comment by vpetersson** [comment]
I'm sure there are valid situations where that works (just like you're mentioning). However, I think it would be misleading for us to say there is a 'kiosk mode' in OSE without properly addressing the concerns raised above.

**Comment by leonardobravi** [comment]
Follow jallen2281 instruction to enable cursor.
If you need to hide it on inactivity (like me) use this code:
`sudo apt-get install unclutter` to install unclutter
`DISPLAY=:0.0 ; export DISPLAY && unclutter -idle 5 -root` to start process, where 5 is the seconds of inactivity. You can use also decimal value like 0.5.

**Comment by noelboss** [comment]
> Change `ExecStart=/usr/bin/matchbox-window-manager -use_titlebar no -use_cursor no` to `ExecStart=/usr/bin/matchbox-window-manager -use_titlebar no -use_cursor yes` in /etc/systemd/system/matchbox.service, and reboot your pi and you should see your mouse working. We use mice with a number of our screenly Pi's

I could not find this file on my installation (latest release) and after creating it and rebooting, mouse or keyboard did not show up. Do you know how to get mouse and keyboard working on the latest releases?

**Comment by vpetersson** [comment]
Hi All,

Screenly is really not designed (nor will it be) to be used in kiosk mode. There are other solutions out there that are far better suited for that use case.
