### ISSUE TITLE
Using GPIO as input for interactivity

### ISSUE THREAD

**Issue by s-celles** [Screenly/Anthias#241]
Hello,

I think that an interesting feature for Screenly could be to add interactivity using Raspberry Pi GPIO.
2 buttons could be used for "Next" / "Previous".

If you want your Python code not to rely on too specific Raspberry Pi functions you should have a look at 
Pingo http://www.pingo.io/docs/ but I think it's only using polling no interrupts

On the other side there is also RPi.GPIO
http://sourceforge.net/projects/raspberry-gpio-python/
which supports interrupts but which is only for Raspberry Pi

if you prefer C code wiringPi http://wiringpi.com/ could be a solution

An other idea to add interactivity is to use an USB keyboard controller with (only) 2 keys.
http://www.instructables.com/id/Hacking-a-USB-Keyboard/

Kind regards

**Comment by abrenoch** [comment]
This is something I would like to see implemented as well (not necessarily for the GPIO specifically), I was thinking of trying to toss together a shell script or something of the liking that would utilize LIRC to advance the slideshow.. Assuming something like that would be able to work with screenly without any significant changes!

**Comment by scls19fr** [comment]
A related blog post
https://www.screenly.io/blog/2017/04/10/how-to-add-a-physical-button-to-screenly-ose-using-node-red/
