### ISSUE TITLE
Migrate to Django

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Anthias#558]
In order to reduce the complexity in our own code base, I'd like to begin the migration to Django of both `viewer.py` and `server.py`. Going forward, that should help us with both maintenances as well as being able to quickly add new features.

**Comment by vpetersson** [comment]
Not worth the effort. Let's instead move to Flask, which is better supported.

**Comment by nicomiguelino** [comment]
#1821 was already merged into the `experimental` branch. Migration of data will be done in #1913.
