### ISSUE TITLE
Disabling Overscan breaks auto-login

### ISSUE THREAD

**Issue by DShearon** [Screenly/Anthias#786]
I am using a Rpi B+ and have been running into an issue. With over-scan enabled everything works and boots properly. When I disable over-scan autorun does not work and I am presented with a login prompt. re-enabling over-scan allows it to boot properly so it is repeatable. I am using the latest version of Screenly OSE.

**Comment by DShearon** [comment]
Is the B+ no longer supported? The process works fine on any of the RPi 3's I try it on. Everything else works fine and is stable on the B+ until I disable overscan. I've confirmed that it is not the SD card or the image itself.

**Comment by vpetersson** [comment]
Are you talking about the original Raspberry Pi Model B+ or the Raspberry Pi 3 Model B+? If the former, it's not a device we're actively testing against. It probably works unless it has been dropped from Raspbian.

**Comment by DShearon** [comment]
The one I am having issues with is the original. I have done some more testing and found that if I disable overscan using the config.txt file it appears to work fine. Disabling overscan using Raspi-config consistently breaks it. Not sure how much help that is for you guys. When I have a moment I will try the same on one of the 3's I have to see if it gets the same result.
