### ISSUE TITLE
Add support for times of day

### ISSUE THREAD

**Issue by acid-nine** [Screenly/Anthias#791]
I have a need where certain 'frames' should be shown at certain times of day (i.e. traffic between 4:00pm-6:00pm).  Vendors who are on premise need to have their logos up while they are there, usually scheduled events.

This could also be prioritized so that other asset frames are not shown during this time.

Let me know if I can help, I'm a Sr Dev with Python and rdbms

**Comment by antonmolodykh** [comment]
Such functionality is available in Screenly Pro, but not in OSE. However, you can use the API (`/api/docs`).
