### ISSUE TITLE
six

### ISSUE THREAD

**Issue by umeboshi2** [Screenly/Anthias#884]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

I couldn't find where ```six``` was being used in the code.  It seems to be added at d60931f4771aeb6ce9d6edf9cedce1b2f5626234 "Improved uptime logic"

Is this project preparing for a transition to python3 before the EOL in 2020?

I have started adjusting ```settings.py``` to use six.  I noticed that passwords are being hashed if the ```len() != 64```, yet no salt is being used.  Why are you hashing passwords without salt?  The ```bcrypt``` package works great for storing hashed passwords.

Here is what I have so far for ```settings.py```.  I'll send a PR when I finish this module.

```diff
diff --git a/settings.py b/settings.py
index 05e7e84..48f6913 100644
--- a/settings.py
+++ b/settings.py
@@ -1,17 +1,24 @@
 #!/usr/bin/env python
 # -*- coding: utf-8 -*-
 
-from os import path, getenv
+from os import path, getenv, makedirs
 from sys import exit
 from time import sleep
-import ConfigParser
+import six
+from six.moves import configparser as ConfigParser
 import logging
-from UserDict import IterableUserDict
+from six.moves import UserDict as IterableUserDict
 from flask import request, Response
 from functools import wraps
 import zmq
 import hashlib
 
+# replace unicode with str in py > 2
+if not six.PY2:
+    unicode = str
+
+
+
 CONFIG_DIR = '.screenly/'
 CONFIG_FILE = 'screenly.conf'
 DEFAULTS = {
@@ -69,8 +76,11 @@ class ScreenlySettings(IterableUserDict):
         self.conf_file = self.get_configfile()
 
         if not path.isfile(self.conf_file):
-            logging.error('Config-file %s missing. Using defaults.', self.conf_file)
+            logging.error('Config-file %s missing. Using defaults.',
+                          self.conf_file)
             self.use_defaults()
+            # ensure parent directories exist.
+            makedirs(path.dirname(self.conf_file))
             self.save()
         else:
             self.load()
```

**Comment by antonmolodykh** [comment]
@umeboshi2 no, you don't need to use the docker environment. Tests were written taking into account that it will be run on a desktop machine and CI.
To run the tests, you can just run `nosetests -v -a '!fixme' --with-isolation`. See the preparatory steps [here](https://github.com/Screenly/screenly-ose/blob/master/.travis.yml).

**Comment by umeboshi2** [comment]
@antonmolodykh Thanks!  I didn't even notice the travis file.  If you have any guidance or preference on how you want the "sixed up" code to look, please let me know.  Much of how this is done is largely matters of taste and preference, and I would like to make something acceptable.

**Comment by umeboshi2** [comment]
Hey, this ```rtmp.py``` in the tests is pretty horrendous!  I know it's not your code, but I'm not sure how to handle the problem.  I patched it to use print functions, but it's really ugly, and it looks like upstream isn't committed to doing much with this code.

**Comment by umeboshi2** [comment]
I ran ```autopep8``` on the rtmp code.  It is still messy.  It seems that exec has changed from a statement to a function, but I never noticed.  I have generally considered the use of exec to be a bad practice.  I sent these changes in an upstream PR, but I seriously doubt that the code is being used by anybody anymore.  It may be beneficial to call the rtmp.py with ```python2``` explicitly and only change after python2 is no longer available on travis.  This should allow the tests to run on both python 2 and 3.  It's Friday evening now, and I'm going to take a break for a bit.  Y'all have a good weekend.
