### ISSUE TITLE
'Unable to resolve local IP address' after reboot of device

### ISSUE THREAD

**Issue by ssantora002** [Screenly/Anthias#925]
Overview of the Issue

Install Screenly OSE from GitHub image 2018-05-04-Screenly_OSE_4GB (latest version) Raspberry Pi Zero w/WiFi. Everything works as expected until I reboot the device. After reboot the screenly splash screen says 'Unable to resolve local IP address'

Reproduction Steps

Steps to reproduce this issue, eg:

* Flash Screenly OSE from GitHub image 2018-05-04-Screenly_OSE_4GB to SD Card
* Boot device
* Connect to Screenly's SSID
* Configure WiFi information.
* Screenly then display local IP.
* Verify connectivity to local address via web browser
* Connect keyboard to raspberry pi and enable SSH
* Enable SSH in raspi-config
* Open raspi-config to set hostname, timezone, and WiFi country.
* Reboot  

When the device completes rebooting it returns the splash screen and the message says, 'Unable to resolve local IP address'

I confirmed the WiFi is running and signal has not been dropped. I've tried re-flashing and starting from scratch, but this time I run the upgrade script before rebooting. After upgrading, if I reboot, the device returns the 'Unable to resolve local IP address' message again.

Environment

* Raspberry Pi Hardware Version: Raspberry Pi Zero w/WiFi on 16GB micro sd card
* Screenly OSE Version: latest github image with latest screenly ose upgrade.

**Comment by vpetersson** [comment]
@ssantora002 Are you able to reproduce this on the latest version?
