### ISSUE TITLE
Plymouth and installation bash

### ISSUE THREAD

**Issue by NikFort** [Screenly/Anthias#926]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
When i install my Lite image and then i try to install screenly with the command there comes no "Picture" on the Screeen only the Command Promt. But ok i can use also the preinstalled image from screenly, but then i want to get a new loadingsscreen, but tere wont come up a nother loading screen when i upload a picture, only this grey background with the 3 loading points. So please can you help me to disable all other things and get a new loading screen, i got it in an older version but not in this one.
A paragraph or two about the issue you're experiencing.
*edit: not even the normal screenly splash has shown up.
### Environment

* Raspberry Pi Hardware Version: Raspberry Pi 2
* Screenly OSE Version: the newset aviable on github

**Comment by rusko124** [comment]
Hi, @NikFort ! 
Could you try make upgrade with the latest changes?(Some edits were made for similar cases when 3 loading points instead of Screenly splashscreen.)
And let me know if this helped you?
