### ISSUE TITLE
Why Screenly needs internet?

### ISSUE THREAD

**Issue by Okhan97** [Screenly/Anthias#994]
Hi,

For my job I need that Screenly starts without internet connection, surfing the web (and the terms of service) I notice that Screenly **kinda needs** confirmation from your server, as Viktor said:

> No, unfortunately you cannot use Screenly without an internet connection. In order to use Screenly the nodes must be able to access our servers.

Is there a reason for this? Everything that I'm doing is local so I was wonder the reason of this restriction.
Is there a way to skip the confirmation from your server?

(I'm asking because you're open source and it doesn't says I can't on the terms of service)

**Comment by Okhan97** [comment]
@vpetersson I think I didn't express myself clear.

The RasPi will be connected to its own router, this router won't have an internet connection (necessarily). I want to be able to upload images and videos directly to the RasPi from another machine connected to the same router (since both machines are in the same network they don't need internet).

Is there an easy way to do this?

**Comment by vpetersson** [comment]
Please see the linked article. It explains how to accomplish that.
